export const employees = [
    {
        art: "Цифровой банк для людей",
        clan: "Database",
        command: "Аквариум",
        directorate: "Дирекция платформенных решений",
        email: "olimpi18@strotransneftegaz.com",
        id: "a5f6d458-0d45-4809-afb9-47d389ce9bee",
        latitude: "85.3975705",
        lead: "Афанасьев Всеслав Андреевич",
        logo: "https://i.pravatar.cc/236",
        longitude: "72.791718",
        manager: "Евгения Вадимовна Смирнова",
        name: "Виктория Тимофеевна Голубева",
        phone: "8 831 437 2818",
        position: "Танкист",
        stream: "PM Team - Продуктовая фабрика",
        telegram: "@koshelevaglafira",
    },
    {
        art: "Цифровые инвестиции",
        clan: "Аналитики",
        command: "Аквариум",
        directorate: "Направление развития единой платформы банковских услуг",
        email: "mirandreev@rossiskaja.ru",
        id: "6fea6c7d-dd60-4f74-8e29-1e509af083a1",
        latitude: "16.528382",
        lead: "Савелий Глебович Матвеев",
        logo: "https://i.pravatar.cc/236",
        longitude: "-10.533578",
        manager: "г-жа Третьякова Надежда Оскаровна",
        name: "Александрова Синклитикия Ивановна",
        phone: "8 815 176 31 44",
        position: "Машинист",
        stream: "КЭП",
        telegram: "@natalja2000",
    },
    {
        art: "Модернизация процесса кросс-продаж кредитных продуктов ФЛ",
        clan: "QA",
        command: "Loan",
        directorate:
            "Дирекция развития технологий корпоративного и инвестиционного бизнеса",
        email: "vorontsovavarvara@gmail.com",
        id: "878bdd4c-3d81-424c-ae95-a1f324027764",
        latitude: "47.830530",
        lead: "Рогов Евстафий Всеволодович",
        logo: "https://i.pravatar.cc/236",
        longitude: "117.345611",
        manager: "Твердислав Иларионович Гордеев",
        name: "Анисимов Эмиль Брониславович",
        phone: "+76109058606",
        position: "Садовод",
        stream: "КЭП",
        telegram: "@aleksandr_2021",
    },
    {
        art: "Цифровые инвестиции",
        clan: "QA",
        command: "Аквариум",
        directorate:
            "Дирекция развития технологий корпоративного и инвестиционного бизнеса",
        email: "samuil2010@kiselev.info",
        id: "07890acc-70e6-4b73-a1c3-8c22a018f9b3",
        latitude: "-13.6534185",
        lead: "Гаврила Данилович Хохлов",
        logo: "https://i.pravatar.cc/236",
        longitude: "-75.756286",
        manager: "Григорий Федосьевич Сысоев",
        name: "Ладимир Брониславович Беляев",
        phone: "+7 110 546 0019",
        position: "Проводник",
        stream: "Вклады и комиссионные продукты",
        telegram: "@haritonovairina",
    },
    {
        art: "Антифрод",
        clan: "DevOps",
        command: "PM Team - Кредитование",
        directorate: "Дирекция качества и развития производственных процессов",
        email: "petr_1982@panov.org",
        id: "d3463ca2-910d-4d97-bcae-a4eed0929a4b",
        latitude: "-50.866168",
        lead: "Шилов Ратибор Ануфриевич",
        logo: "https://i.pravatar.cc/236",
        longitude: "112.480301",
        manager: "Матвеев Модест Федосеевич",
        name: "Дроздова Варвара Макаровна",
        phone: "+7 205 069 51 52",
        position: "Гитарист",
        stream: "PM Team - Продуктовая фабрика",
        telegram: "@kliment_1986",
    },
    {
        art: "Кредитный конвейер КБ",
        clan: "Front-end",
        command: "Аквариум",
        directorate: "Отдел по работе с персоналом",
        email: "makarovevdokim@hotmail.com",
        id: "17b723fb-951b-4f82-a47c-1b1d3d0848dd",
        latitude: "-32.9863885",
        lead: "Гремислав Анисимович Туров",
        logo: "https://i.pravatar.cc/236",
        longitude: "134.362383",
        manager: "Гуляев Гедеон Иларионович",
        name: "Остромир Филиппович Бобров",
        phone: "8 (218) 620-80-50",
        position: "Фрезеровщик",
        stream: "Вклады и комиссионные продукты",
        telegram: "@evstigne_83",
    },
    {
        art: "Кредитный конвейер КБ",
        clan: "Аналитики",
        command: "Аквариум",
        directorate: "Административный отдел",
        email: "alekseevatamara@hotmail.com",
        id: "34f6be06-9fd2-4ba1-ad20-94bdb1b8b30a",
        latitude: "26.0372385",
        lead: "Ефим Григорьевич Соловьев",
        logo: "https://i.pravatar.cc/236",
        longitude: "-126.521880",
        manager: "Борислав Филатович Алексеев",
        name: "Боброва Маргарита Мироновна",
        phone: "+78884008200",
        position: "Сыровар",
        stream: "КЭП",
        telegram: "@zsharova",
    },
    {
        art: "Роботизация процессов",
        clan: "Database",
        command: "PM Team - Кредитование",
        directorate: "Направление Ак Барс Коннект",
        email: "zfokin@ooo.edu",
        id: "9e478ffe-9f5d-43a3-8af2-a8c53b85648f",
        latitude: "63.770199",
        lead: "Медведева Нина Вадимовна",
        logo: "https://i.pravatar.cc/236",
        longitude: "-26.889416",
        manager: "Андроник Евсеевич Волков",
        name: "София Федоровна Назарова",
        phone: "+7 551 897 5685",
        position: "Востоковед",
        stream: "Вклады и комиссионные продукты",
        telegram: "@cfrolov",
    },
    {
        art: "Внешние инновации",
        clan: "DevOps",
        command: "Loan",
        directorate: "Дирекция инновационного развития и маркетинга",
        email: "sila_91@yahoo.com",
        id: "03f877fa-6c13-4bb0-974d-b44ffde6d263",
        latitude: "28.2073745",
        lead: "Борисова Октябрина Анатольевна",
        logo: "https://i.pravatar.cc/236",
        longitude: "159.046062",
        manager: "Богданов Эрнест Ерофеевич",
        name: "Исакова Ирина Кирилловна",
        phone: "8 793 732 94 83",
        position: "Танатолог",
        stream: "PM Team - Продуктовая фабрика",
        telegram: "@regina2015",
    },
    {
        art: "HR Digital",
        clan: "Front-end",
        command: "PM Team - Кредитование",
        directorate: "Дирекция технологического развития и внутренних решений",
        email: "zhukovratmir@hotmail.com",
        id: "570a67df-cc4f-4acf-8d92-c16b12825830",
        latitude: "80.5545765",
        lead: "Маргарита Кузьминична Ларионова",
        logo: "https://i.pravatar.cc/236",
        longitude: "-101.160592",
        manager: "Кошелев Панфил Авдеевич",
        name: "Майя Геннадьевна Боброва",
        phone: "+7 664 286 1783",
        position: "Священнослужитель",
        stream: "Вклады и комиссионные продукты",
        telegram: "@ljubomirfedorov",
    },
];
